name: sqflite
homepage: https://github.com/tekartik/sqflite/tree/master/sqflite
description: Flutter plugin for SQLite, a self-contained, high-reliability,
  embedded, SQL database engine.
version: 2.0.2

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.10.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.tekartik.sqflite
        pluginClass: SqflitePlugin
      ios:
        pluginClass: SqflitePlugin
      macos:
        pluginClass: SqflitePlugin

dependencies:
  flutter:
    sdk: flutter
  # sqflite_common: '>=2.0.1 <4.0.0'
  sqflite_common:
    git:
      url: https://github.com/fachrifaul/sqflite.git
      path: sqflite_common
      ref: v2.0.2-web
  path: '>=1.8.0 <3.0.0'

dev_dependencies:
  flutter_lints: '>=1.0.0'
  process_run: '>=0.12.0'
  http: '>=0.13.0'
  flutter_test:
    sdk: flutter
  test_api: '>=0.2.19'
  pub_semver: '>=2.0.0'
